import { DevelopmentCardType } from "types/DevelopmentCardType"

const shuffle = <T>(items: T[]) => {
  return items
    .map(value => ({ value, sort: Math.random() }))
    .sort((a, b) => a.sort - b.sort)
    .map(({ value }) => value)
}

export const levelOneDevelopmentCards: DevelopmentCardType[] = shuffle([
  {
    prestigePoints: 0,
    bonus: "Sapphire",
    numberOfDiamondsRequiredToBuy: 1,
    numberOfSapphiresRequiredToBuy: 0,
    numberOfEmeraldsRequiredToBuy: 1,
    numberOfRubiesRequiredToBuy: 2,
    numberOfOnyxesRequiredToBuy: 1,
  },
  {
    prestigePoints: 0,
    bonus: "Emerald",
    numberOfDiamondsRequiredToBuy: 1,
    numberOfSapphiresRequiredToBuy: 3,
    numberOfEmeraldsRequiredToBuy: 1,
    numberOfRubiesRequiredToBuy: 0,
    numberOfOnyxesRequiredToBuy: 0,
  },
  {
    prestigePoints: 0,
    bonus: "Emerald",
    numberOfDiamondsRequiredToBuy: 1,
    numberOfSapphiresRequiredToBuy: 1,
    numberOfEmeraldsRequiredToBuy: 0,
    numberOfRubiesRequiredToBuy: 1,
    numberOfOnyxesRequiredToBuy: 1,
  },
  {
    prestigePoints: 0,
    bonus: "Ruby",
    numberOfDiamondsRequiredToBuy: 1,
    numberOfSapphiresRequiredToBuy: 1,
    numberOfEmeraldsRequiredToBuy: 1,
    numberOfRubiesRequiredToBuy: 0,
    numberOfOnyxesRequiredToBuy: 1,
  },
  {
    prestigePoints: 0,
    bonus: "Ruby",
    numberOfDiamondsRequiredToBuy: 1,
    numberOfSapphiresRequiredToBuy: 0,
    numberOfEmeraldsRequiredToBuy: 0,
    numberOfRubiesRequiredToBuy: 1,
    numberOfOnyxesRequiredToBuy: 3,
  },
  {
    prestigePoints: 0,
    bonus: "Ruby",
    numberOfDiamondsRequiredToBuy: 0,
    numberOfSapphiresRequiredToBuy: 2,
    numberOfEmeraldsRequiredToBuy: 1,
    numberOfRubiesRequiredToBuy: 0,
    numberOfOnyxesRequiredToBuy: 0,
  },
  {
    prestigePoints: 0,
    bonus: "Onyx",
    numberOfDiamondsRequiredToBuy: 1,
    numberOfSapphiresRequiredToBuy: 2,
    numberOfEmeraldsRequiredToBuy: 1,
    numberOfRubiesRequiredToBuy: 1,
    numberOfOnyxesRequiredToBuy: 0,
  },
  {
    prestigePoints: 0,
    bonus: "Onyx",
    numberOfDiamondsRequiredToBuy: 0,
    numberOfSapphiresRequiredToBuy: 0,
    numberOfEmeraldsRequiredToBuy: 3,
    numberOfRubiesRequiredToBuy: 0,
    numberOfOnyxesRequiredToBuy: 0,
  },
  {
    prestigePoints: 0,
    bonus: "Onyx",
    numberOfDiamondsRequiredToBuy: 0,
    numberOfSapphiresRequiredToBuy: 0,
    numberOfEmeraldsRequiredToBuy: 2,
    numberOfRubiesRequiredToBuy: 1,
    numberOfOnyxesRequiredToBuy: 0,
  },
  {
    prestigePoints: 0,
    bonus: "Onyx",
    numberOfDiamondsRequiredToBuy: 0,
    numberOfSapphiresRequiredToBuy: 0,
    numberOfEmeraldsRequiredToBuy: 1,
    numberOfRubiesRequiredToBuy: 3,
    numberOfOnyxesRequiredToBuy: 1,
  },
  {
    prestigePoints: 0,
    bonus: "Onyx",
    numberOfDiamondsRequiredToBuy: 1,
    numberOfSapphiresRequiredToBuy: 1,
    numberOfEmeraldsRequiredToBuy: 1,
    numberOfRubiesRequiredToBuy: 1,
    numberOfOnyxesRequiredToBuy: 0,
  },
  {
    prestigePoints: 0,
    bonus: "Diamond",
    numberOfDiamondsRequiredToBuy: 3,
    numberOfSapphiresRequiredToBuy: 1,
    numberOfEmeraldsRequiredToBuy: 0,
    numberOfRubiesRequiredToBuy: 0,
    numberOfOnyxesRequiredToBuy: 1,
  },
  {
    prestigePoints: 1,
    bonus: "Diamond",
    numberOfDiamondsRequiredToBuy: 0,
    numberOfSapphiresRequiredToBuy: 0,
    numberOfEmeraldsRequiredToBuy: 4,
    numberOfRubiesRequiredToBuy: 0,
    numberOfOnyxesRequiredToBuy: 0,
  },
  {
    prestigePoints: 0,
    bonus: "Ruby",
    numberOfDiamondsRequiredToBuy: 2,
    numberOfSapphiresRequiredToBuy: 0,
    numberOfEmeraldsRequiredToBuy: 0,
    numberOfRubiesRequiredToBuy: 2,
    numberOfOnyxesRequiredToBuy: 0,
  },
  {
    prestigePoints: 0,
    bonus: "Ruby",
    numberOfDiamondsRequiredToBuy: 2,
    numberOfSapphiresRequiredToBuy: 0,
    numberOfEmeraldsRequiredToBuy: 1,
    numberOfRubiesRequiredToBuy: 0,
    numberOfOnyxesRequiredToBuy: 2,
  },
  {
    prestigePoints: 1,
    bonus: "Onyx",
    numberOfDiamondsRequiredToBuy: 0,
    numberOfSapphiresRequiredToBuy: 4,
    numberOfEmeraldsRequiredToBuy: 0,
    numberOfRubiesRequiredToBuy: 0,
    numberOfOnyxesRequiredToBuy: 0,
  },
  {
    prestigePoints: 0,
    bonus: "Sapphire",
    numberOfDiamondsRequiredToBuy: 1,
    numberOfSapphiresRequiredToBuy: 0,
    numberOfEmeraldsRequiredToBuy: 2,
    numberOfRubiesRequiredToBuy: 2,
    numberOfOnyxesRequiredToBuy: 0,
  },
  {
    prestigePoints: 1,
    bonus: "Sapphire",
    numberOfDiamondsRequiredToBuy: 0,
    numberOfSapphiresRequiredToBuy: 0,
    numberOfEmeraldsRequiredToBuy: 0,
    numberOfRubiesRequiredToBuy: 4,
    numberOfOnyxesRequiredToBuy: 0,
  },
  {
    prestigePoints: 0,
    bonus: "Sapphire",
    numberOfDiamondsRequiredToBuy: 0,
    numberOfSapphiresRequiredToBuy: 1,
    numberOfEmeraldsRequiredToBuy: 3,
    numberOfRubiesRequiredToBuy: 1,
    numberOfOnyxesRequiredToBuy: 0,
  },
  {
    prestigePoints: 0,
    bonus: "Sapphire",
    numberOfDiamondsRequiredToBuy: 0,
    numberOfSapphiresRequiredToBuy: 0,
    numberOfEmeraldsRequiredToBuy: 2,
    numberOfRubiesRequiredToBuy: 0,
    numberOfOnyxesRequiredToBuy: 2,
  },
  {
    prestigePoints: 0,
    bonus: "Diamond",
    numberOfDiamondsRequiredToBuy: 0,
    numberOfSapphiresRequiredToBuy: 2,
    numberOfEmeraldsRequiredToBuy: 0,
    numberOfRubiesRequiredToBuy: 0,
    numberOfOnyxesRequiredToBuy: 2,
  },
  {
    prestigePoints: 0,
    bonus: "Diamond",
    numberOfDiamondsRequiredToBuy: 0,
    numberOfSapphiresRequiredToBuy: 2,
    numberOfEmeraldsRequiredToBuy: 2,
    numberOfRubiesRequiredToBuy: 0,
    numberOfOnyxesRequiredToBuy: 1,
  },
  {
    prestigePoints: 1,
    bonus: "Ruby",
    numberOfDiamondsRequiredToBuy: 4,
    numberOfSapphiresRequiredToBuy: 0,
    numberOfEmeraldsRequiredToBuy: 0,
    numberOfRubiesRequiredToBuy: 0,
    numberOfOnyxesRequiredToBuy: 0,
  },
  {
    prestigePoints: 0,
    bonus: "Onyx",
    numberOfDiamondsRequiredToBuy: 2,
    numberOfSapphiresRequiredToBuy: 2,
    numberOfEmeraldsRequiredToBuy: 0,
    numberOfRubiesRequiredToBuy: 1,
    numberOfOnyxesRequiredToBuy: 0,
  },
  {
    prestigePoints: 0,
    bonus: "Diamond",
    numberOfDiamondsRequiredToBuy: 0,
    numberOfSapphiresRequiredToBuy: 3,
    numberOfEmeraldsRequiredToBuy: 0,
    numberOfRubiesRequiredToBuy: 0,
    numberOfOnyxesRequiredToBuy: 0,
  },
  {
    prestigePoints: 0,
    bonus: "Diamond",
    numberOfDiamondsRequiredToBuy: 0,
    numberOfSapphiresRequiredToBuy: 0,
    numberOfEmeraldsRequiredToBuy: 0,
    numberOfRubiesRequiredToBuy: 2,
    numberOfOnyxesRequiredToBuy: 1,
  },
  {
    prestigePoints: 0,
    bonus: "Diamond",
    numberOfDiamondsRequiredToBuy: 0,
    numberOfSapphiresRequiredToBuy: 1,
    numberOfEmeraldsRequiredToBuy: 1,
    numberOfRubiesRequiredToBuy: 1,
    numberOfOnyxesRequiredToBuy: 1,
  },
  {
    prestigePoints: 0,
    bonus: "Emerald",
    numberOfDiamondsRequiredToBuy: 2,
    numberOfSapphiresRequiredToBuy: 1,
    numberOfEmeraldsRequiredToBuy: 0,
    numberOfRubiesRequiredToBuy: 0,
    numberOfOnyxesRequiredToBuy: 0,
  },
  {
    prestigePoints: 0,
    bonus: "Emerald",
    numberOfDiamondsRequiredToBuy: 0,
    numberOfSapphiresRequiredToBuy: 2,
    numberOfEmeraldsRequiredToBuy: 0,
    numberOfRubiesRequiredToBuy: 2,
    numberOfOnyxesRequiredToBuy: 0,
  },
  {
    prestigePoints: 0,
    bonus: "Diamond",
    numberOfDiamondsRequiredToBuy: 0,
    numberOfSapphiresRequiredToBuy: 1,
    numberOfEmeraldsRequiredToBuy: 2,
    numberOfRubiesRequiredToBuy: 1,
    numberOfOnyxesRequiredToBuy: 1,
  },
  {
    prestigePoints: 0,
    bonus: "Emerald",
    numberOfDiamondsRequiredToBuy: 0,
    numberOfSapphiresRequiredToBuy: 0,
    numberOfEmeraldsRequiredToBuy: 0,
    numberOfRubiesRequiredToBuy: 3,
    numberOfOnyxesRequiredToBuy: 0,
  },
  {
    prestigePoints: 0,
    bonus: "Onyx",
    numberOfDiamondsRequiredToBuy: 2,
    numberOfSapphiresRequiredToBuy: 0,
    numberOfEmeraldsRequiredToBuy: 2,
    numberOfRubiesRequiredToBuy: 0,
    numberOfOnyxesRequiredToBuy: 0,
  },
  {
    prestigePoints: 0,
    bonus: "Ruby",
    numberOfDiamondsRequiredToBuy: 3,
    numberOfSapphiresRequiredToBuy: 0,
    numberOfEmeraldsRequiredToBuy: 0,
    numberOfRubiesRequiredToBuy: 0,
    numberOfOnyxesRequiredToBuy: 0,
  },
  {
    prestigePoints: 0,
    bonus: "Ruby",
    numberOfDiamondsRequiredToBuy: 2,
    numberOfSapphiresRequiredToBuy: 1,
    numberOfEmeraldsRequiredToBuy: 1,
    numberOfRubiesRequiredToBuy: 0,
    numberOfOnyxesRequiredToBuy: 1,
  },
  {
    prestigePoints: 0,
    bonus: "Sapphire",
    numberOfDiamondsRequiredToBuy: 1,
    numberOfSapphiresRequiredToBuy: 0,
    numberOfEmeraldsRequiredToBuy: 1,
    numberOfRubiesRequiredToBuy: 1,
    numberOfOnyxesRequiredToBuy: 1,
  },
  {
    prestigePoints: 0,
    bonus: "Sapphire",
    numberOfDiamondsRequiredToBuy: 1,
    numberOfSapphiresRequiredToBuy: 0,
    numberOfEmeraldsRequiredToBuy: 0,
    numberOfRubiesRequiredToBuy: 0,
    numberOfOnyxesRequiredToBuy: 2,
  },
  {
    prestigePoints: 0,
    bonus: "Sapphire",
    numberOfDiamondsRequiredToBuy: 0,
    numberOfSapphiresRequiredToBuy: 0,
    numberOfEmeraldsRequiredToBuy: 0,
    numberOfRubiesRequiredToBuy: 0,
    numberOfOnyxesRequiredToBuy: 3,
  },
  {
    prestigePoints: 1,
    bonus: "Emerald",
    numberOfDiamondsRequiredToBuy: 0,
    numberOfSapphiresRequiredToBuy: 0,
    numberOfEmeraldsRequiredToBuy: 0,
    numberOfRubiesRequiredToBuy: 0,
    numberOfOnyxesRequiredToBuy: 4,
  },
  {
    prestigePoints: 0,
    bonus: "Emerald",
    numberOfDiamondsRequiredToBuy: 1,
    numberOfSapphiresRequiredToBuy: 1,
    numberOfEmeraldsRequiredToBuy: 0,
    numberOfRubiesRequiredToBuy: 1,
    numberOfOnyxesRequiredToBuy: 2,
  },
  {
    prestigePoints: 0,
    bonus: "Emerald",
    numberOfDiamondsRequiredToBuy: 0,
    numberOfSapphiresRequiredToBuy: 1,
    numberOfEmeraldsRequiredToBuy: 0,
    numberOfRubiesRequiredToBuy: 2,
    numberOfOnyxesRequiredToBuy: 2,
  },
])

export const levelTwoDevelopmentCards: DevelopmentCardType[] = shuffle([
  {
    prestigePoints: 2,
    bonus: "Onyx",
    numberOfDiamondsRequiredToBuy: 0,
    numberOfSapphiresRequiredToBuy: 0,
    numberOfEmeraldsRequiredToBuy: 5,
    numberOfRubiesRequiredToBuy: 3,
    numberOfOnyxesRequiredToBuy: 0,
  },
  {
    prestigePoints: 2,
    bonus: "Emerald",
    numberOfDiamondsRequiredToBuy: 0,
    numberOfSapphiresRequiredToBuy: 0,
    numberOfEmeraldsRequiredToBuy: 5,
    numberOfRubiesRequiredToBuy: 0,
    numberOfOnyxesRequiredToBuy: 0,
  },
  {
    prestigePoints: 1,
    bonus: "Emerald",
    numberOfDiamondsRequiredToBuy: 3,
    numberOfSapphiresRequiredToBuy: 0,
    numberOfEmeraldsRequiredToBuy: 2,
    numberOfRubiesRequiredToBuy: 3,
    numberOfOnyxesRequiredToBuy: 0,
  },
  {
    prestigePoints: 1,
    bonus: "Ruby",
    numberOfDiamondsRequiredToBuy: 2,
    numberOfSapphiresRequiredToBuy: 0,
    numberOfEmeraldsRequiredToBuy: 0,
    numberOfRubiesRequiredToBuy: 2,
    numberOfOnyxesRequiredToBuy: 3,
  },
  {
    prestigePoints: 2,
    bonus: "Onyx",
    numberOfDiamondsRequiredToBuy: 5,
    numberOfSapphiresRequiredToBuy: 0,
    numberOfEmeraldsRequiredToBuy: 0,
    numberOfRubiesRequiredToBuy: 0,
    numberOfOnyxesRequiredToBuy: 0,
  },
  {
    prestigePoints: 2,
    bonus: "Emerald",
    numberOfDiamondsRequiredToBuy: 0,
    numberOfSapphiresRequiredToBuy: 5,
    numberOfEmeraldsRequiredToBuy: 3,
    numberOfRubiesRequiredToBuy: 0,
    numberOfOnyxesRequiredToBuy: 0,
  },
  {
    prestigePoints: 1,
    bonus: "Sapphire",
    numberOfDiamondsRequiredToBuy: 0,
    numberOfSapphiresRequiredToBuy: 2,
    numberOfEmeraldsRequiredToBuy: 3,
    numberOfRubiesRequiredToBuy: 0,
    numberOfOnyxesRequiredToBuy: 3,
  },
  {
    prestigePoints: 1,
    bonus: "Diamond",
    numberOfDiamondsRequiredToBuy: 2,
    numberOfSapphiresRequiredToBuy: 3,
    numberOfEmeraldsRequiredToBuy: 0,
    numberOfRubiesRequiredToBuy: 3,
    numberOfOnyxesRequiredToBuy: 0,
  },
  {
    prestigePoints: 3,
    bonus: "Diamond",
    numberOfDiamondsRequiredToBuy: 6,
    numberOfSapphiresRequiredToBuy: 0,
    numberOfEmeraldsRequiredToBuy: 0,
    numberOfRubiesRequiredToBuy: 0,
    numberOfOnyxesRequiredToBuy: 0,
  },
  {
    prestigePoints: 2,
    bonus: "Sapphire",
    numberOfDiamondsRequiredToBuy: 5,
    numberOfSapphiresRequiredToBuy: 3,
    numberOfEmeraldsRequiredToBuy: 0,
    numberOfRubiesRequiredToBuy: 0,
    numberOfOnyxesRequiredToBuy: 0,
  },
  {
    prestigePoints: 1,
    bonus: "Sapphire",
    numberOfDiamondsRequiredToBuy: 0,
    numberOfSapphiresRequiredToBuy: 2,
    numberOfEmeraldsRequiredToBuy: 2,
    numberOfRubiesRequiredToBuy: 3,
    numberOfOnyxesRequiredToBuy: 0,
  },
  {
    prestigePoints: 3,
    bonus: "Emerald",
    numberOfDiamondsRequiredToBuy: 0,
    numberOfSapphiresRequiredToBuy: 0,
    numberOfEmeraldsRequiredToBuy: 6,
    numberOfRubiesRequiredToBuy: 0,
    numberOfOnyxesRequiredToBuy: 0,
  },
  {
    prestigePoints: 3,
    bonus: "Sapphire",
    numberOfDiamondsRequiredToBuy: 0,
    numberOfSapphiresRequiredToBuy: 6,
    numberOfEmeraldsRequiredToBuy: 0,
    numberOfRubiesRequiredToBuy: 0,
    numberOfOnyxesRequiredToBuy: 0,
  },
  {
    prestigePoints: 2,
    bonus: "Sapphire",
    numberOfDiamondsRequiredToBuy: 2,
    numberOfSapphiresRequiredToBuy: 0,
    numberOfEmeraldsRequiredToBuy: 0,
    numberOfRubiesRequiredToBuy: 1,
    numberOfOnyxesRequiredToBuy: 4,
  },
  {
    prestigePoints: 1,
    bonus: "Emerald",
    numberOfDiamondsRequiredToBuy: 2,
    numberOfSapphiresRequiredToBuy: 3,
    numberOfEmeraldsRequiredToBuy: 0,
    numberOfRubiesRequiredToBuy: 0,
    numberOfOnyxesRequiredToBuy: 2,
  },
  {
    prestigePoints: 3,
    bonus: "Onyx",
    numberOfDiamondsRequiredToBuy: 0,
    numberOfSapphiresRequiredToBuy: 0,
    numberOfEmeraldsRequiredToBuy: 0,
    numberOfRubiesRequiredToBuy: 0,
    numberOfOnyxesRequiredToBuy: 6,
  },
  {
    prestigePoints: 2,
    bonus: "Emerald",
    numberOfDiamondsRequiredToBuy: 4,
    numberOfSapphiresRequiredToBuy: 2,
    numberOfEmeraldsRequiredToBuy: 0,
    numberOfRubiesRequiredToBuy: 0,
    numberOfOnyxesRequiredToBuy: 1,
  },
  {
    prestigePoints: 2,
    bonus: "Diamond",
    numberOfDiamondsRequiredToBuy: 0,
    numberOfSapphiresRequiredToBuy: 0,
    numberOfEmeraldsRequiredToBuy: 0,
    numberOfRubiesRequiredToBuy: 5,
    numberOfOnyxesRequiredToBuy: 0,
  },
  {
    prestigePoints: 2,
    bonus: "Diamond",
    numberOfDiamondsRequiredToBuy: 0,
    numberOfSapphiresRequiredToBuy: 0,
    numberOfEmeraldsRequiredToBuy: 0,
    numberOfRubiesRequiredToBuy: 5,
    numberOfOnyxesRequiredToBuy: 3,
  },
  {
    prestigePoints: 2,
    bonus: "Diamond",
    numberOfDiamondsRequiredToBuy: 0,
    numberOfSapphiresRequiredToBuy: 0,
    numberOfEmeraldsRequiredToBuy: 1,
    numberOfRubiesRequiredToBuy: 4,
    numberOfOnyxesRequiredToBuy: 2,
  },
  {
    prestigePoints: 1,
    bonus: "Diamond",
    numberOfDiamondsRequiredToBuy: 0,
    numberOfSapphiresRequiredToBuy: 0,
    numberOfEmeraldsRequiredToBuy: 3,
    numberOfRubiesRequiredToBuy: 2,
    numberOfOnyxesRequiredToBuy: 2,
  },
  {
    prestigePoints: 3,
    bonus: "Ruby",
    numberOfDiamondsRequiredToBuy: 0,
    numberOfSapphiresRequiredToBuy: 0,
    numberOfEmeraldsRequiredToBuy: 0,
    numberOfRubiesRequiredToBuy: 6,
    numberOfOnyxesRequiredToBuy: 0,
  },
  {
    prestigePoints: 2,
    bonus: "Ruby",
    numberOfDiamondsRequiredToBuy: 3,
    numberOfSapphiresRequiredToBuy: 0,
    numberOfEmeraldsRequiredToBuy: 0,
    numberOfRubiesRequiredToBuy: 0,
    numberOfOnyxesRequiredToBuy: 5,
  },
  {
    prestigePoints: 2,
    bonus: "Ruby",
    numberOfDiamondsRequiredToBuy: 0,
    numberOfSapphiresRequiredToBuy: 0,
    numberOfEmeraldsRequiredToBuy: 0,
    numberOfRubiesRequiredToBuy: 0,
    numberOfOnyxesRequiredToBuy: 5,
  },
  {
    prestigePoints: 1,
    bonus: "Onyx",
    numberOfDiamondsRequiredToBuy: 3,
    numberOfSapphiresRequiredToBuy: 0,
    numberOfEmeraldsRequiredToBuy: 3,
    numberOfRubiesRequiredToBuy: 0,
    numberOfOnyxesRequiredToBuy: 2,
  },
  {
    prestigePoints: 1,
    bonus: "Onyx",
    numberOfDiamondsRequiredToBuy: 3,
    numberOfSapphiresRequiredToBuy: 2,
    numberOfEmeraldsRequiredToBuy: 2,
    numberOfRubiesRequiredToBuy: 0,
    numberOfOnyxesRequiredToBuy: 0,
  },
  {
    prestigePoints: 2,
    bonus: "Onyx",
    numberOfDiamondsRequiredToBuy: 0,
    numberOfSapphiresRequiredToBuy: 1,
    numberOfEmeraldsRequiredToBuy: 4,
    numberOfRubiesRequiredToBuy: 2,
    numberOfOnyxesRequiredToBuy: 0,
  },
  {
    prestigePoints: 2,
    bonus: "Ruby",
    numberOfDiamondsRequiredToBuy: 1,
    numberOfSapphiresRequiredToBuy: 4,
    numberOfEmeraldsRequiredToBuy: 2,
    numberOfRubiesRequiredToBuy: 0,
    numberOfOnyxesRequiredToBuy: 0,
  },
  {
    prestigePoints: 1,
    bonus: "Ruby",
    numberOfDiamondsRequiredToBuy: 0,
    numberOfSapphiresRequiredToBuy: 3,
    numberOfEmeraldsRequiredToBuy: 0,
    numberOfRubiesRequiredToBuy: 2,
    numberOfOnyxesRequiredToBuy: 3,
  },
  {
    prestigePoints: 2,
    bonus: "Sapphire",
    numberOfDiamondsRequiredToBuy: 0,
    numberOfSapphiresRequiredToBuy: 5,
    numberOfEmeraldsRequiredToBuy: 0,
    numberOfRubiesRequiredToBuy: 0,
    numberOfOnyxesRequiredToBuy: 0,
  },
])

export const levelThreeDevelopmentCards: DevelopmentCardType[] = shuffle([
  {
    prestigePoints: 3,
    bonus: "Onyx",
    numberOfDiamondsRequiredToBuy: 3,
    numberOfSapphiresRequiredToBuy: 3,
    numberOfEmeraldsRequiredToBuy: 5,
    numberOfRubiesRequiredToBuy: 3,
    numberOfOnyxesRequiredToBuy: 0,
  },
  {
    prestigePoints: 4,
    bonus: "Ruby",
    numberOfDiamondsRequiredToBuy: 0,
    numberOfSapphiresRequiredToBuy: 3,
    numberOfEmeraldsRequiredToBuy: 6,
    numberOfRubiesRequiredToBuy: 3,
    numberOfOnyxesRequiredToBuy: 0,
  },
  {
    prestigePoints: 3,
    bonus: "Ruby",
    numberOfDiamondsRequiredToBuy: 3,
    numberOfSapphiresRequiredToBuy: 5,
    numberOfEmeraldsRequiredToBuy: 3,
    numberOfRubiesRequiredToBuy: 0,
    numberOfOnyxesRequiredToBuy: 3,
  },
  {
    prestigePoints: 4,
    bonus: "Emerald",
    numberOfDiamondsRequiredToBuy: 3,
    numberOfSapphiresRequiredToBuy: 6,
    numberOfEmeraldsRequiredToBuy: 3,
    numberOfRubiesRequiredToBuy: 0,
    numberOfOnyxesRequiredToBuy: 0,
  },
  {
    prestigePoints: 4,
    bonus: "Diamond",
    numberOfDiamondsRequiredToBuy: 0,
    numberOfSapphiresRequiredToBuy: 0,
    numberOfEmeraldsRequiredToBuy: 0,
    numberOfRubiesRequiredToBuy: 0,
    numberOfOnyxesRequiredToBuy: 7,
  },
  {
    prestigePoints: 5,
    bonus: "Sapphire",
    numberOfDiamondsRequiredToBuy: 7,
    numberOfSapphiresRequiredToBuy: 3,
    numberOfEmeraldsRequiredToBuy: 0,
    numberOfRubiesRequiredToBuy: 0,
    numberOfOnyxesRequiredToBuy: 0,
  },
  {
    prestigePoints: 4,
    bonus: "Emerald",
    numberOfDiamondsRequiredToBuy: 0,
    numberOfSapphiresRequiredToBuy: 7,
    numberOfEmeraldsRequiredToBuy: 0,
    numberOfRubiesRequiredToBuy: 0,
    numberOfOnyxesRequiredToBuy: 0,
  },
  {
    prestigePoints: 5,
    bonus: "Emerald",
    numberOfDiamondsRequiredToBuy: 0,
    numberOfSapphiresRequiredToBuy: 7,
    numberOfEmeraldsRequiredToBuy: 3,
    numberOfRubiesRequiredToBuy: 0,
    numberOfOnyxesRequiredToBuy: 0,
  },
  {
    prestigePoints: 4,
    bonus: "Onyx",
    numberOfDiamondsRequiredToBuy: 0,
    numberOfSapphiresRequiredToBuy: 0,
    numberOfEmeraldsRequiredToBuy: 3,
    numberOfRubiesRequiredToBuy: 6,
    numberOfOnyxesRequiredToBuy: 3,
  },
  {
    prestigePoints: 3,
    bonus: "Emerald",
    numberOfDiamondsRequiredToBuy: 5,
    numberOfSapphiresRequiredToBuy: 3,
    numberOfEmeraldsRequiredToBuy: 0,
    numberOfRubiesRequiredToBuy: 3,
    numberOfOnyxesRequiredToBuy: 3,
  },
  {
    prestigePoints: 4,
    bonus: "Ruby",
    numberOfDiamondsRequiredToBuy: 0,
    numberOfSapphiresRequiredToBuy: 0,
    numberOfEmeraldsRequiredToBuy: 7,
    numberOfRubiesRequiredToBuy: 0,
    numberOfOnyxesRequiredToBuy: 0,
  },
  {
    prestigePoints: 5,
    bonus: "Diamond",
    numberOfDiamondsRequiredToBuy: 3,
    numberOfSapphiresRequiredToBuy: 0,
    numberOfEmeraldsRequiredToBuy: 0,
    numberOfRubiesRequiredToBuy: 0,
    numberOfOnyxesRequiredToBuy: 7,
  },
  {
    prestigePoints: 4,
    bonus: "Sapphire",
    numberOfDiamondsRequiredToBuy: 7,
    numberOfSapphiresRequiredToBuy: 0,
    numberOfEmeraldsRequiredToBuy: 0,
    numberOfRubiesRequiredToBuy: 0,
    numberOfOnyxesRequiredToBuy: 0,
  },
  {
    prestigePoints: 3,
    bonus: "Sapphire",
    numberOfDiamondsRequiredToBuy: 3,
    numberOfSapphiresRequiredToBuy: 0,
    numberOfEmeraldsRequiredToBuy: 3,
    numberOfRubiesRequiredToBuy: 3,
    numberOfOnyxesRequiredToBuy: 5,
  },
  {
    prestigePoints: 5,
    bonus: "Onyx",
    numberOfDiamondsRequiredToBuy: 0,
    numberOfSapphiresRequiredToBuy: 0,
    numberOfEmeraldsRequiredToBuy: 0,
    numberOfRubiesRequiredToBuy: 7,
    numberOfOnyxesRequiredToBuy: 3,
  },
  {
    prestigePoints: 5,
    bonus: "Ruby",
    numberOfDiamondsRequiredToBuy: 0,
    numberOfSapphiresRequiredToBuy: 0,
    numberOfEmeraldsRequiredToBuy: 7,
    numberOfRubiesRequiredToBuy: 3,
    numberOfOnyxesRequiredToBuy: 0,
  },
  {
    prestigePoints: 4,
    bonus: "Diamond",
    numberOfDiamondsRequiredToBuy: 3,
    numberOfSapphiresRequiredToBuy: 0,
    numberOfEmeraldsRequiredToBuy: 0,
    numberOfRubiesRequiredToBuy: 3,
    numberOfOnyxesRequiredToBuy: 6,
  },
  {
    prestigePoints: 4,
    bonus: "Sapphire",
    numberOfDiamondsRequiredToBuy: 6,
    numberOfSapphiresRequiredToBuy: 3,
    numberOfEmeraldsRequiredToBuy: 0,
    numberOfRubiesRequiredToBuy: 0,
    numberOfOnyxesRequiredToBuy: 3,
  },
  {
    prestigePoints: 3,
    bonus: "Diamond",
    numberOfDiamondsRequiredToBuy: 0,
    numberOfSapphiresRequiredToBuy: 3,
    numberOfEmeraldsRequiredToBuy: 3,
    numberOfRubiesRequiredToBuy: 5,
    numberOfOnyxesRequiredToBuy: 3,
  },
  {
    prestigePoints: 4,
    bonus: "Onyx",
    numberOfDiamondsRequiredToBuy: 0,
    numberOfSapphiresRequiredToBuy: 0,
    numberOfEmeraldsRequiredToBuy: 0,
    numberOfRubiesRequiredToBuy: 7,
    numberOfOnyxesRequiredToBuy: 0,
  },
])

const developmentCards = {
  levelOneDevelopmentCards,
  levelTwoDevelopmentCards,
  levelThreeDevelopmentCards,
}

export default developmentCards
